name: Continuous Integration

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Next.js Build
      run: npm run build

    - name: Merge to Master
      if: success() # Only run this step if the build is successful
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git fetch
        git checkout master
        git merge --ff-only staging
        git push origin master
